repos:
  - repo: local
    hooks:
      - id: radon-complexity-check
        name: Check Cyclomatic Complexity
        entry: bash -c 'radon cc -s -n B $(git diff --cached --name-only --diff-filter=ACM | grep -E "\.py$")'
        language: system
        types: [python]